version: '2'
services:
    node:
        image: "ghcr.io/kabuspl/oceny-backend:latest"
        environment:
            DISCORD_WEBHOOK_NORMAL_GRADES: "https://discord.com/api/webhooks/123/abc"
            DISCORD_WEBHOOK_SEMESTRAL_GRADES: "https://discord.com/api/webhooks/123/abc"
            DISCORD_WEBHOOK_ERRORS: "https://discord.com/api/webhooks/123/abc"
            UONET_USERNAME: "student@school.com"
            UONET_PASSWORD: "P@ssw0rd"
            UONET_SYMBOL: "city"
            UPDATE_RATE_MS: 300000
            LOG_LEVEL: 2
        volumes:
            - datastore:/home/node/app/datastore
            - logs:/home/node/app/logs
            - ./datastore_import:/home/node/app/datastore_import
        ports:
            - "4080"
volumes:
    datastore:
    logs: