version: '2'
services:
    node:
        image: "node:latest"
        user: "node"
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
        expose:
            - "4080"
        command: "node ."